# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('gad1', '0003_filedb'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='stat',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
