# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gad1', '0002_auto_20170821_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.FileField(upload_to='source')),
            ],
        ),
    ]
